orders/urls.py
from django.urls import path
from .views import add_to_cart, OrderList,chackout_page ,process_payment,payment_failed,payment_success
from .api import CartDetailCreateDeleteAPI, OrderDetailAPI , OrderListAPI , CreateOrderAPI


app_name = "orders"

urlpatterns = [
    path('' , OrderList.as_view()),
    path('add-to-cart' , add_to_cart ,name='add_to_cart'),
    path('checkout' , chackout_page),
    path('checkout/payment' , process_payment),
    path('checkout/payment/success' , payment_success),
    path('checkout/payment/failed' , payment_failed),
    # api
    path('api/<str:username>/cart' , CartDetailCreateDeleteAPI.as_view()),
    path('api/<str:username>/cart/create-order' , CreateOrderAPI.as_view()),

    path('api/<str:username>/orders' , OrderListAPI.as_view()),
    path('api/<str:username>/orders/<int:pk>' , OrderDetailAPI.as_view()),
]

products/urls.py
from django.urls import path
from .views import ProductList,ProductDetail ,BrandList,BrandDetail,post_list_debug,add_review
from .api import ProductListAPI , ProductDetailAPI,BrandListAPI,BrandDetailAPI


app_name='products'

urlpatterns = [
    path('debug',post_list_debug),
    path('',ProductList.as_view(),name='product_list'),
    path('<slug:slug>',ProductDetail.as_view(),name='product_detail'),
    path('<slug:slug>/review/add',add_review,name='add_review'),
    path('brand/',BrandList.as_view(),name='brand_list'),
    path('brand/<slug:slug>',BrandDetail.as_view(),name='brand_detail'),
    # api 
    path('api/list' , ProductListAPI.as_view()),
    path('api/list/<int:pk>' , ProductDetailAPI.as_view()),
    path('brands/api/list' , BrandListAPI.as_view()),
    path('brands/api/list/<int:pk>' , BrandDetailAPI.as_view()),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

from settings.views import home
from rest_framework_simplejwt.views import (
TokenObtainPairView,
TokenRefreshView,
)

schema_view = get_schema_view(

openapi.Info(
title="Amazon Clone API",
default_version='v1',
description="Django Amazon Clone API",
terms_of_service="",
contact=openapi.Contact(email="contact@snippets.local"),
license=openapi.License(name="BSD License"),
),
public=True,
permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
path("accounts/", include("django.contrib.auth.urls")),
path('accounts/',include('accounts.urls')),
path('admin/', admin.site.urls),
path('products/', include('products.urls',namespace='products')),
path('',home),
path('orders/', include('orders.urls',namespace='orders')) ,
path("__debug__/", include("debug_toolbar.urls")),
path('summernote/', include('django_summernote.urls')),
#path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
#path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
path('dj-rest-auth/', include('dj_rest_auth.urls')),
path("i18n/", include("django.conf.urls.i18n")),
path('rosetta/', include('rosetta.urls')),
path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
from taggit.managers import TaggableManager
from django.utils.translation import gettext_lazy as _
from django.utils.text import slugify
from django.db.models.aggregates import Avg , Sum,Count


FLAG_TYPES = (
    ('New','New'),
    ('Sale','Sale'),
    ('Feature','Feature'),
)
# Create your models here.
class Product(models.Model):
    name = models.CharField(_('name'),max_length=120)
    description = models.TextField(_('description'),max_length=30000)
    sku = models.IntegerField(_('sku'))
    price = models.FloatField(_('price'))
    subtitle = models.TextField(_('subtitle'),max_length=600)
    image = models.ImageField(_('image'),upload_to='products')
    brand = models.ForeignKey('Brand' , verbose_name=_('brand'),on_delete=models.CASCADE,related_name='product_brand')
    flag = models.CharField(_('flag'),max_length=20,choices=FLAG_TYPES)
    tags = TaggableManager()
    slug = models.SlugField(null=True,blank=True)
    video = models.URLField(null=True,blank=True)

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)    
        super(Product, self).save(*args, **kwargs) 
    
    
    def get_avg_rate(self):
        avg = self.product_review.aggregate(avg=Avg('rate'))
        return avg

class ProductImages(models.Model):
    product = models.ForeignKey(Product,verbose_name=_('product'),related_name='product_images',on_delete=models.CASCADE)
    image = models.ImageField(_('image'),upload_to='product_images')
    

    

class Brand(models.Model):
    name = models.CharField(_('name'),max_length=100)
    image = models.ImageField(_('image'),upload_to='brand')
    slug = models.SlugField(null=True,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)    
        super(Brand, self).save(*args, **kwargs)

    def get_avg_rate(self):
        'brand --> products ---> avg'
        data = Product.objects.filter(brand=self)
        avg = []
        for p in data:
            product_rates = p.product_review.aggregate(avg=Avg('rate'))
            if product_rates['avg'] != None:
                avg.append(product_rates['avg'])


        if len(avg) ==0 :
            result = 0
        else:
            result = sum(avg)/len(avg)
        return result

    def get_rate_count(self):
        data = Product.objects.filter(brand=self)
        result = 0
        for p in data:
            product_rates = p.product_review.aggregate(count=Count('id'))
            result += product_rates['count']
        return result
        
         

class Review(models.Model):
    user = models.ForeignKey(User,verbose_name=_('user'),related_name='user_review',on_delete=models.SET_NULL,null=True,blank=True)
    product = models.ForeignKey(Product,verbose_name=_('product'),related_name='product_review',on_delete=models.SET_NULL,null=True,blank=True)
    review = models.TextField(_('review'),max_length=500)
    rate = models.IntegerField(_('rate'),validators=[MaxValueValidator(5),MinValueValidator(0)])
    create_date = models.DateTimeField(_('create date'),default=timezone.now)

    def __str__(self):
        return f"{self.user} = {self.product}"

products/forms.py
from django import forms 
from .models import Review



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['review','rate']

products/views.py
from django.shortcuts import render,redirect
from django.views import generic
from .forms import ReviewForm
from .models import Product , ProductImages , Review,Brand
from django.db.models import Q , F , Value , Func
from django.db.models.aggregates import Count,Avg,Sum,Min,Max
from django.conf import settings
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from .tasks import send_m_email

#@cache_page(60 * 1)
def post_list_debug(request):

    # data = Product.objects.all()
    # data = Product.objects.filter(price=20)
    # data = Product.objects.filter(price__gt=80)
    # data = Product.objects.filter(price__gte=80)
    # data = Product.objects.filter(price__lt=80)
    # data = Product.objects.filter(price__lte=80)
    # data = Product.objects.filter(price__range=(24,25))

    # data = Product.objects.filter(brand__id=1)
    # data = Product.objects.filter(brand__id__gt=30)

    # data = Product.objects.filter(name__contains='snyder')
    # data = Product.objects.filter(name__startswith='Logan')
    # data = Product.objects.filter(name__endswith='Snyder')
    # data = Product.objects.filter(video__isnull=True)

    # data = Review.objects.filter(create_date__year=2023)
    # data = Review.objects.filter(create_date__month=7)

    # data = Product.objects.filter(price__gt=50,flag='Sale')
    # data = Product.objects.filter(price__gt=50).filter(flag='Sale')


    # data = Product.objects.filter(
    #     Q(price__gt=95) |
    #     Q(flag='Sale')
    # )

    # data = Product.objects.filter(
    #     Q(price__gt=95) &
    #     Q(flag='Sale')
    # )

    # data = Product.objects.filter(
    #     Q(price__gt=95) &
    #     ~Q(flag='Sale')
    # )

    # data = Product.objects.filter(sku=F('price'))
    # data = Product.objects.filter(sku=F('brand__id'))

    # data = Product.objects.all().order_by('name') # ASC
    # data = Product.objects.all().order_by('-name') # DES

    # data = Product.objects.order_by('-name') # DES
    # data = Product.objects.filter(brand__id=1).order_by('name')
    # data = Product.objects.order_by('flag','name')
    # data = Product.objects.order_by('flag','name')[0]
    # data = Product.objects.earliest('flag','name')
    # data = Product.objects.last()


    # data = Product.objects.all()[:5]
    # data = Product.objects.all()[5:10]


    # data = Product.objects.values('name','price','flag','brand__name')
    # data = Product.objects.values_list('name','price','flag','brand__name')
    # data = Product.objects.values_list('name','price','flag','brand__name').distinct()

    # data = Product.objects.only('name','price','flag','brand__name')
    # data = Product.objects.defer('description')


    # data = Product.objects.select_related('brand').all()  # select_related : one-to-one , one-to-many
    # data = Product.objects.prefetch_related('brand').all()  # prefetch_related : many-to-many

    # data = Product.objects.aggregate(Min('price'))
    # data = Product.objects.aggregate(mymin = Min('price'))
    # data = Product.objects.aggregate(mymin = Min('price'),mycount=Count('id'))


    # data = Product.objects.annotate(is_new=Value(True))
    # data = Product.objects.annotate(price_with_tax=F('price')*1.2)
    #data = Brand.objects.annotate(posts=Count('product_brand'))
    data = Product.objects.all()
    # send email 1m user
    send_m_email.delay()
    return render(request,'products/debug.html',{'data':data})

@method_decorator(cache_page(60 * 5), name='dispatch')
class ProductList(generic.ListView):
    model = Product
    paginate_by=settings.MYPAGINATION


class ProductDetail(generic.DetailView):
    model = Product
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["reviews"] = Review.objects.filter(product=self.get_object())
        return context

def add_review(request,slug):
        product = Product.objects.get(slug=slug)
        form = ReviewForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user = request.user
            myform.product = product
            myform.save()
            reviews = Review.objects.filter(product=product)
            html = render_to_string('include/all_reviews.html',{'reviews':reviews , request:request})
            return JsonResponse({'result':html})    



class BrandList(generic.ListView):
    model = Brand
    paginate_by=50
    
    
    def get_queryset(self):
        object_list = Brand.objects.annotate(posts_count=Count('product_brand'))
        return object_list 


class BrandDetail(generic.ListView):
    model = Product
    template_name='products/brand_detail.html'

    def get_queryset(self):
        brand =  Brand.objects.get(slug=self.kwargs['slug'])
        queryset = Product.objects.filter(brand=brand)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["brand"] = Brand.objects.filter(slug=self.kwargs['slug']).annotate(posts_count=Count('product_brand'))[0]
        return context

products/templates/products/brand_detail.html
{% extends "base.html" %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'ltr/css/brand-single.css' %}">
{% endblock css %}
{% block body %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star {% if brand.get_avg_rate > 0 %} active {% endif %}"></li>
                <li class="fas fa-star {% if brand.get_avg_rate > 1 %} active {% endif %}"></li>
                <li class="fas fa-star {% if brand.get_avg_rate > 2 %} active {% endif %}"></li>
                <li class="fas fa-star {% if brand.get_avg_rate > 3 %} active {% endif %}"></li>
                <li class="fas fa-star {% if brand.get_avg_rate > 4 %} active {% endif %}"></li>
                <li class="total">({{brand.get_rate_count}} ratings)</li>
            </ul>
            <p>({{brand.posts_count}} items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                {% for product in object_list %}          
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{product.flag}}</label>
                                    </div>
                                    <button class="product-wish wish">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                    <a class="product-image" href="{% url 'products:product_detail' product.slug %}">
                                        <img src="{{product.image.url}}" alt="product">
                                    </a>
                                    <div class="product-widget">
                                        <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                        <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                        <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                             <i class="icofont-star {% if product.get_avg_rate.avg > 0 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 1 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 2 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 3 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 4 %} active {% endif %}"></i>
                                        <a href="product-video.html">({{product.product_review.all|length}})</a>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:product_detail' product.slug %}">{{product}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        <span>${{product.price}}<small>/piece</small></span>
                                    </h6>
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="bottom-paginate">
                            <p class="page-info">Showing 12 of 60 Results</p>
                            <ul class="pagination">
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-left"></i>
                                    </a>
                                </li>
                                <li class="page-item"><a class="page-link active" href="#">1</a></li>
                                <li class="page-item"><a class="page-link" href="#">2</a></li>
                                <li class="page-item"><a class="page-link" href="#">3</a></li>
                                <li class="page-item">...</li>
                                <li class="page-item"><a class="page-link" href="#">60</a></li>
                                <li class="page-item">
                                    <a class="page-link" href="#">
                                        <i class="fas fa-long-arrow-alt-right"></i>
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
        {% endblock body %}

products/templates/products/debug.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
</head>

<body>
    <h1>Posts</h1>

    <ul>
        {% for post in data %}
        <li>{{post}} - {{post.brand}}</li>
        {% endfor %}
    </ul>
</body>

</html>

products/templates/products/product_list.html
{% extends "base.html" %}
{% block body %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Shop 5 Column</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">shop-5column</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                            <div class="filter-action">
                                <a href="shop-3column.html" title="Three Column"><i class="fas fa-th"></i></a>
                                <a href="shop-2column.html" title="Two Column"><i class="fas fa-th-large"></i></a>
                                <a href="shop-1column.html" title="One Column"><i class="fas fa-th-list"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                {% for product in object_list  %}
                   
                   
                        <div class="col">
                            <div class="product-card">
                                <div class="product-media">
                                    <div class="product-label">
                                        <label class="label-text new">{{product.flag}}</label>
                                    </div>
                                    <button class="product-wish wish">
                                        <i class="fas fa-heart"></i>
                                    </button>
                                    <a class="product-image" href="{% url 'products:product_detail' product.slug %}">
                                        <img src="{{product.image.url}}" alt="product">
                                    </a>
                                    <div class="product-widget">
                                        <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                        <a title="Product Video" href="{{product.video}}" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                        <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                    </div>
                                </div>
                                <div class="product-content">
                                    <div class="product-rating">
                                          <i class="icofont-star {% if product.get_avg_rate.avg > 0 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 1 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 2 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 3 %} active {% endif %}"></i>
                                        <i class="icofont-star {% if product.get_avg_rate.avg > 4 %} active {% endif %}"></i>
                                        <a href="product-video.html">({{product.product_review.all|length}})</a>
                                    </div>
                                    <h6 class="product-name">
                                        <a href="{% url 'products:product_detail' product.slug %}">{{product}}</a>
                                    </h6>
                                    <h6 class="product-price">
                                        
                                        <span>${{product.price}}<small>/piece</small></span>
                                    </h6>
                                    <button class="product-add" title="Add to Cart">
                                        <i class="fas fa-shopping-basket"></i>
                                        <span>add</span>
                                    </button>
                                    <div class="product-action">
                                        <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                        <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                        <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                    </div>
                                </div>
                            </div>
                        </div>
                  
                {% endfor %}
                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previous_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}


                                    {% for i in paginator.page_range  %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>

                                        {% elif i > page_obj.number|add:'-5' and i < page_obj.number|add:'5' %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}       


                                    {% endfor %}

                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
{% endblock body %}